var FCConstants = require('../constants/fc-constants');
var FCDispatcher = require('../dispatcher/fc-dispatcher');

var FCActions = {

    /**
     * Register a reference to the audio object
     * @param {object} audio
     */
    registerAudio: function( audio ){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.REGISTER_AUDIO,
            audio: audio
        });
    },

    /**
     * Recorder not available for this user or browser
     */
    recorderNotAllowable: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.RECORDER_NOT_ALLOWABLE
        });
    },

    /**
     * Register a reference to the recording object
     * @param {object} recorder
     */
    registerRecorder: function( recorder ){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.REGISTER_RECORDER,
            recorder: recorder
        });
    },

    /**
     * Starts the recording the events on the code editor
     */
    startRecordingVideo: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.START_RECORDING_VIDEO
        });
    },

    /**
    * Starts the recording the audio for the screencast
    */
    startRecordingAudio: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.START_RECORDING_AUDIO
        });
    },

    /**
     * Lifecycle event to have any changes occur after the start of the recording
     */
    startMainPhaseRecording: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.MAIN_PHASE_RECORDING
        });
    },


    captureCodingEvent: function( evt ){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.CODING_EVENT,
            event: evt
        });
    },

    /**
    * Stop recording the video
    */
    stopRecordingVideo: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.STOP_RECORDING_VIDEO
        });
    },

    /**
    * Handles stop recording audio
    */
    stopRecordingAudio: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.STOP_RECORDING_AUDIO
        });
    },

    /**
     * Registers the audio file that was generated by recorder
     * @param audioFile
     */
    registerAudioFile: function(audioFile){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.REGISTER_AUDIO_FILE,
            audioFile: audioFile
        })
    },

    /**
     * Play back the audio file
     */
    playbackAudio: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.PLAYBACK_AUDIO
        });
    },

    /**
     * Play back the video file
     */
    playbackVideo: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.PLAYBACK_VIDEO
        });
    },

    /**
     * Registers the interval id of the event loop running for key events
     * @param intervalId
     */
    registerPlaybackIntervalId: function( playbackIntervalId ){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.REGISTER_PLAYBACK_INTERVAL_ID,
            playbackIntervalId: playbackIntervalId
        });
    },

    pauseAudio: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.PAUSE_AUDIO
        });
    },

    pauseVideo: function(){
        FCDispatcher.handleViewAction({
            actionType: FCConstants.PAUSE_VIDEO
        });
    }

    //
    ///**
    // * Creates a playable video format that can be played by application
    // * @param {eventLog} The events that have been recorded and logged.
    // * @return {video} The index of the callback within the _callbacks array.
    // */
    //createVideoFormat: function( eventLog ){
    //    FCDispatcher.handleViewAction({
    //        actionType: FCConstants.CREATE_VIDEO_FORMAT,
    //        eventLog: eventLog
    //    });
    //}
};

module.exports = FCActions;
